# Generated by Django 5.2.11 on 2026-02-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='deal',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(default='New Deal', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.deal'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='New Ticket', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
