# Generated by Django 5.2.11 on 2026-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_deal_title_remove_ticket_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
