# Generated by Django 5.2.11 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_city_company_country_company_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
