# Generated by Django 5.2.11 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
